### New User
POST http://localhost:4000/auth/signup
Content-Type: application/json

{
  "nickname": "radaman",
  "email": "rada@gmail.com",
  "password": "Seba2010!",
  "confirmPassword": "Seba2010!"
}

### Login

POST  http://localhost:4000/auth/signin
Content-Type: application/json

{
   "email": "rada@gmail.com",
   "password": "Seba2010!"
}