### New User
POST http://localhost:4000/graphql

Content-Type: application/json

{
    "nickname": "Braulio",
    "email": "example@mail.com",
    "password": "seba2010",
}

### Get User

GET http://localhost:4000/users/1